#!/bin/sh

function usage () {
	echo "enable/disable partwized auto-mode"
	echo "execute following command:"
	echo "	$0 on #enable auto-mode"
	echo "	$0 off #disable auto-mode"
}

case $1 in
	on)
		echo "enable partwized auto-mode"
		echo "pwized=\"\""
		#env pwized=""
		unset pwized
	;;
	off)
		echo "disable partwized auto-mode"
		echo "pwized=\"1\""
#		env pwized="1"
		export pwized="1"
	;;
	*)
		usage
	;;
esac

